services:
#  http.oauth: 
#    class: GuzzleHttp\Subscriber\Oauth\Oauth1
#    arguments: [{ consumer_key: %trello_api_token%, consumer_secret: %trello_api_secret% }]
#
#  http.client.emitter:
#    class: ~
#    factory_service: http.client
#    factory_method: getEmitter
#    calls:
#      - [attach, ["@http.oauth"]]

  trello.controller.home:
    class: Webforge\Trello\Controller\HomeController
    calls:
      - [setContainer, ["@service_container"]]

  http.client:
    class: GuzzleHttp\Client
    arguments: [{ base_url: %http_endpoint%, defaults: { query: { key: %trello_api_key%, token: %trello_api_token% } } }]

  trello.api:
    class: Webforge\Trello\Api
    arguments: ["@http.client", "@event_dispatcher", "@trello.synchronizer"]

  trello.synchronizer:
    class: Webforge\Trello\Synchronizer
    arguments: ["@event_dispatcher", "@doctrine.orm.entity_manager"]